---
- name: Crear directorio base /tmp/2do_parcial
  ansible.builtin.file:
    path: /tmp/2do_parcial
    state: directory
    mode: '0755'

- name: Crear directorio alumno
  ansible.builtin.file:
    path: /tmp/2do_parcial/alumno
    state: directory
    mode: '0755'

- name: Crear directorio equipo
  ansible.builtin.file:
    path: /tmp/2do_parcial/equipo
    state: directory
    mode: '0755'

- name: Generar datos_alumno.txt
  ansible.builtin.template:
    src: datos_alumno.txt.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt
    mode: '0644'

- name: Generar datos_equipo.txt
  ansible.builtin.template:
    src: datos_equipo.txt.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt
    mode: '0644'

- name: Asegurar que el grupo 2PSupervisores exista
  ansible.builtin.group:
    name: 2PSupervisores
    state: present

- name: Configurar sudoers para 2PSupervisores (NOPASSWD)
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/2psupervisores_nopasswd
    state: present
    create: yes
    mode: '0440'
    line: '%2PSupervisores ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
